### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by jlxy11** [Tsarpf/procgen#2]
I build it with cmake and vs2019 on my win11 laptop ,but when I try to run it, I came with:
Renderer: Intel(R) UHD Graphics 770
OpenGL version supported 3.2.0 - Build 31.0.101.4502
test
platform win32
constructing new octree at min (0, 0, 0), size 64

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: ...procgen-master\procgen-master\build\Debug\dual-contouring.exe
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector
Line: 1553

Expression: vector subscript out of range

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

**Comment by Tsarpf** [comment]
Hey thanks, I noticed this only now, I will take a look when I have time, but it may be a while.

any chance you could further pinpoint where in my code that vector index lookup comes?

**Comment by Tsarpf** [comment]
Also check out the devel branch, its faster! I don’t remember why it’s not in master yet 😁

**Comment by Tsarpf** [comment]
Ok I merged devel to master. Maybe the error is gone now?

**Comment by jlxy11** [comment]
> Also check out the devel branch, its faster! I don’t remember why it’s not in master yet 😁
Sorry for replying so late! It works! And thanks a lot  for such a great job! @Tsarpf
